package com.example.leagueapp.networking.model.models

data class Participant(
        val participantId : Int = 0,
        val championId : Int = 0,
        val runes : List<Rune> = emptyList(),
        val stats : ParticipantStats = ParticipantStats(),
        val teamId : Int = 0,
        val timeline: ParticipantTimeline = ParticipantTimeline(),
        val summoner1Id : Int = 0,
        val summoner2Id : Int = 0,
        val highestAchievedSeasonTier : String = "",
        val masteries : List<Mastery> = emptyList(),
        val baronKills : Int = 0,
        val bountyLevel : Int = 0,
        val champExperience : Int = 0,
        val championName : String = "",
        val championTransform : Int = 0,
        val consumablesPurchased : Int = 0,
        val itemsPurchased : Int = 0,
        val nexusKills : Int = 0,
        val objectivesStolen : Int = 0,
        val spell1Casts : Int = 0,
        val spell1Id : Int = 0,
        val spell2Casts : Int = 0,
        val spell2Id : Int = 0,
        val spell3Casts : Int = 0,
        val spell4Casts : Int = 0,
        val summoner1Casts : Int = 0,
        val summoner2Casts : Int = 0,
        val timePlayed : Int = 0,
        val totalHealsOnTeammates : Int = 0,
        val objectivesStolenAssists : Int = 0,
        val totalDamageShieldedOnTeammates : Int = 0,
        val totalTimeCCDealt : Int = 0,
        val totalTimeSpentDead : Int = 0,
        val firstBloodAssist : Boolean = false,
        val gameEndedInEarlySurrender : Boolean = false,
        val gameEndedInSurrender : Boolean = false,
        val teamEarlySurrendered : Boolean = false,
        val individualPosition : String = "",
        val riotIdName : String = "",
        val riotIdTagline : String = "",
        val teamPosition : String = "",
        var carryScore : Double = 0.0,
        var isCarry : Boolean = false
)
